# Generated by Django 3.2.7 on 2021-09-17 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Сообщение')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Время отправления')),
                ('read_status', models.IntegerField(verbose_name='Статус')),
                ('mfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('mto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.chat', verbose_name='Получатель')),
            ],
        ),
    ]
