# Generated by Django 3.2.7 on 2021-09-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='mto',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='mfrom',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='message',
            name='read_status',
            field=models.BooleanField(verbose_name='Статус'),
        ),
    ]
